package com.davenotdavid.pokemontrackerapi.pokemon

object PokemonData {
    val ALL: List<Pokemon> = listOf(
        Pokemon(1, "Bulbasaur", listOf("Grass", "Poison"), 45),
        Pokemon(2, "Ivysaur", listOf("Grass", "Poison"), 60),
        Pokemon(3, "Venusaur", listOf("Grass", "Poison"), 80),
        Pokemon(4, "Charmander", listOf("Fire"), 39),
        Pokemon(5, "Charmeleon", listOf("Fire"), 58),
        Pokemon(6, "Charizard", listOf("Fire", "Flying"), 78),
        Pokemon(7, "Squirtle", listOf("Water"), 44),
        Pokemon(8, "Wartortle", listOf("Water"), 59),
        Pokemon(9, "Blastoise", listOf("Water"), 79),
        Pokemon(10, "Caterpie", listOf("Bug"), 45),
        Pokemon(11, "Metapod", listOf("Bug"), 50),
        Pokemon(12, "Butterfree", listOf("Bug", "Flying"), 60),
        Pokemon(13, "Weedle", listOf("Bug", "Poison"), 40),
        Pokemon(14, "Kakuna", listOf("Bug", "Poison"), 45),
        Pokemon(15, "Beedrill", listOf("Bug", "Poison"), 65),
        Pokemon(16, "Pidgey", listOf("Normal", "Flying"), 40),
        Pokemon(17, "Pidgeotto", listOf("Normal", "Flying"), 63),
        Pokemon(18, "Pidgeot", listOf("Normal", "Flying"), 83),
        Pokemon(19, "Rattata", listOf("Normal"), 30),
        Pokemon(20, "Raticate", listOf("Normal"), 55),
        Pokemon(21, "Spearow", listOf("Normal", "Flying"), 40),
        Pokemon(22, "Fearow", listOf("Normal", "Flying"), 65),
        Pokemon(23, "Ekans", listOf("Poison"), 35),
        Pokemon(24, "Arbok", listOf("Poison"), 60),
        Pokemon(25, "Pikachu", listOf("Electric"), 35),
        Pokemon(26, "Raichu", listOf("Electric"), 60),
        Pokemon(27, "Sandshrew", listOf("Ground"), 50),
        Pokemon(28, "Sandslash", listOf("Ground"), 75),
        Pokemon(29, "Nidoran-F", listOf("Poison"), 55),
        Pokemon(30, "Nidorina", listOf("Poison"), 70),
        Pokemon(31, "Nidoqueen", listOf("Poison", "Ground"), 90),
        Pokemon(32, "Nidoran-M", listOf("Poison"), 46),
        Pokemon(33, "Nidorino", listOf("Poison"), 61),
        Pokemon(34, "Nidoking", listOf("Poison", "Ground"), 81),
        Pokemon(35, "Clefairy", listOf("Fairy"), 70),
        Pokemon(36, "Clefable", listOf("Fairy"), 95),
        Pokemon(37, "Vulpix", listOf("Fire"), 38),
        Pokemon(38, "Ninetales", listOf("Fire"), 73),
        Pokemon(39, "Jigglypuff", listOf("Normal", "Fairy"), 115),
        Pokemon(40, "Wigglytuff", listOf("Normal", "Fairy"), 140),
        Pokemon(41, "Zubat", listOf("Poison", "Flying"), 40),
        Pokemon(42, "Golbat", listOf("Poison", "Flying"), 75),
        Pokemon(43, "Oddish", listOf("Grass", "Poison"), 45),
        Pokemon(44, "Gloom", listOf("Grass", "Poison"), 60),
        Pokemon(45, "Vileplume", listOf("Grass", "Poison"), 75),
        Pokemon(46, "Paras", listOf("Bug", "Grass"), 35),
        Pokemon(47, "Parasect", listOf("Bug", "Grass"), 60),
        Pokemon(48, "Venonat", listOf("Bug", "Poison"), 60),
        Pokemon(49, "Venomoth", listOf("Bug", "Poison"), 70),
        Pokemon(50, "Diglett", listOf("Ground"), 10),
        Pokemon(51, "Dugtrio", listOf("Ground"), 35),
        Pokemon(52, "Meowth", listOf("Normal"), 40),
        Pokemon(53, "Persian", listOf("Normal"), 65),
        Pokemon(54, "Psyduck", listOf("Water"), 50),
        Pokemon(55, "Golduck", listOf("Water"), 80),
        Pokemon(56, "Mankey", listOf("Fighting"), 40),
        Pokemon(57, "Primeape", listOf("Fighting"), 65),
        Pokemon(58, "Growlithe", listOf("Fire"), 55),
        Pokemon(59, "Arcanine", listOf("Fire"), 90),
        Pokemon(60, "Poliwag", listOf("Water"), 40),
        Pokemon(61, "Poliwhirl", listOf("Water"), 65),
        Pokemon(62, "Poliwrath", listOf("Water", "Fighting"), 90),
        Pokemon(63, "Abra", listOf("Psychic"), 25),
        Pokemon(64, "Kadabra", listOf("Psychic"), 40),
        Pokemon(65, "Alakazam", listOf("Psychic"), 55),
        Pokemon(66, "Machop", listOf("Fighting"), 70),
        Pokemon(67, "Machoke", listOf("Fighting"), 80),
        Pokemon(68, "Machamp", listOf("Fighting"), 90),
        Pokemon(69, "Bellsprout", listOf("Grass", "Poison"), 50),
        Pokemon(70, "Weepinbell", listOf("Grass", "Poison"), 65),
        Pokemon(71, "Victreebel", listOf("Grass", "Poison"), 80),
        Pokemon(72, "Tentacool", listOf("Water", "Poison"), 40),
        Pokemon(73, "Tentacruel", listOf("Water", "Poison"), 80),
        Pokemon(74, "Geodude", listOf("Rock", "Ground"), 40),
        Pokemon(75, "Graveler", listOf("Rock", "Ground"), 55),
        Pokemon(76, "Golem", listOf("Rock", "Ground"), 80),
        Pokemon(77, "Ponyta", listOf("Fire"), 50),
        Pokemon(78, "Rapidash", listOf("Fire"), 65),
        Pokemon(79, "Slowpoke", listOf("Water", "Psychic"), 90),
        Pokemon(80, "Slowbro", listOf("Water", "Psychic"), 95),
        Pokemon(81, "Magnemite", listOf("Electric", "Steel"), 25),
        Pokemon(82, "Magneton", listOf("Electric", "Steel"), 50),
        Pokemon(83, "Farfetch'd", listOf("Normal", "Flying"), 52),
        Pokemon(84, "Doduo", listOf("Normal", "Flying"), 35),
        Pokemon(85, "Dodrio", listOf("Normal", "Flying"), 60),
        Pokemon(86, "Seel", listOf("Water"), 65),
        Pokemon(87, "Dewgong", listOf("Water", "Ice"), 90),
        Pokemon(88, "Grimer", listOf("Poison"), 80),
        Pokemon(89, "Muk", listOf("Poison"), 105),
        Pokemon(90, "Shellder", listOf("Water"), 30),
        Pokemon(91, "Cloyster", listOf("Water", "Ice"), 50),
        Pokemon(92, "Gastly", listOf("Ghost", "Poison"), 30),
        Pokemon(93, "Haunter", listOf("Ghost", "Poison"), 45),
        Pokemon(94, "Gengar", listOf("Ghost", "Poison"), 60),
        Pokemon(95, "Onix", listOf("Rock", "Ground"), 35),
        Pokemon(96, "Drowzee", listOf("Psychic"), 60),
        Pokemon(97, "Hypno", listOf("Psychic"), 85),
        Pokemon(98, "Krabby", listOf("Water"), 30),
        Pokemon(99, "Kingler", listOf("Water"), 55),
        Pokemon(100, "Voltorb", listOf("Electric"), 40),
        Pokemon(101, "Electrode", listOf("Electric"), 60),
        Pokemon(102, "Exeggcute", listOf("Grass", "Psychic"), 60),
        Pokemon(103, "Exeggutor", listOf("Grass", "Psychic"), 95),
        Pokemon(104, "Cubone", listOf("Ground"), 50),
        Pokemon(105, "Marowak", listOf("Ground"), 60),
        Pokemon(106, "Hitmonlee", listOf("Fighting"), 50),
        Pokemon(107, "Hitmonchan", listOf("Fighting"), 50),
        Pokemon(108, "Lickitung", listOf("Normal"), 90),
        Pokemon(109, "Koffing", listOf("Poison"), 40),
        Pokemon(110, "Weezing", listOf("Poison"), 65),
        Pokemon(111, "Rhyhorn", listOf("Ground", "Rock"), 80),
        Pokemon(112, "Rhydon", listOf("Ground", "Rock"), 105),
        Pokemon(113, "Chansey", listOf("Normal"), 250),
        Pokemon(114, "Tangela", listOf("Grass"), 65),
        Pokemon(115, "Kangaskhan", listOf("Normal"), 105),
        Pokemon(116, "Horsea", listOf("Water"), 30),
        Pokemon(117, "Seadra", listOf("Water"), 55),
        Pokemon(118, "Goldeen", listOf("Water"), 45),
        Pokemon(119, "Seaking", listOf("Water"), 80),
        Pokemon(120, "Staryu", listOf("Water"), 30),
        Pokemon(121, "Starmie", listOf("Water", "Psychic"), 60),
        Pokemon(122, "Mr. Mime", listOf("Psychic", "Fairy"), 40),
        Pokemon(123, "Scyther", listOf("Bug", "Flying"), 70),
        Pokemon(124, "Jynx", listOf("Ice", "Psychic"), 65),
        Pokemon(125, "Electabuzz", listOf("Electric"), 65),
        Pokemon(126, "Magmar", listOf("Fire"), 65),
        Pokemon(127, "Pinsir", listOf("Bug"), 65),
        Pokemon(128, "Tauros", listOf("Normal"), 75),
        Pokemon(129, "Magikarp", listOf("Water"), 20),
        Pokemon(130, "Gyarados", listOf("Water", "Flying"), 95),
        Pokemon(131, "Lapras", listOf("Water", "Ice"), 130),
        Pokemon(132, "Ditto", listOf("Normal"), 48),
        Pokemon(133, "Eevee", listOf("Normal"), 55),
        Pokemon(134, "Vaporeon", listOf("Water"), 130),
        Pokemon(135, "Jolteon", listOf("Electric"), 65),
        Pokemon(136, "Flareon", listOf("Fire"), 65),
        Pokemon(137, "Porygon", listOf("Normal"), 65),
        Pokemon(138, "Omanyte", listOf("Rock", "Water"), 35),
        Pokemon(139, "Omastar", listOf("Rock", "Water"), 70),
        Pokemon(140, "Kabuto", listOf("Rock", "Water"), 30),
        Pokemon(141, "Kabutops", listOf("Rock", "Water"), 60),
        Pokemon(142, "Aerodactyl", listOf("Rock", "Flying"), 80),
        Pokemon(143, "Snorlax", listOf("Normal"), 160),
        Pokemon(144, "Articuno", listOf("Ice", "Flying"), 90),
        Pokemon(145, "Zapdos", listOf("Electric", "Flying"), 90),
        Pokemon(146, "Moltres", listOf("Fire", "Flying"), 90),
        Pokemon(147, "Dratini", listOf("Dragon"), 41),
        Pokemon(148, "Dragonair", listOf("Dragon"), 61),
        Pokemon(149, "Dragonite", listOf("Dragon", "Flying"), 91),
        Pokemon(150, "Mewtwo", listOf("Psychic"), 106),
        Pokemon(151, "Mew", listOf("Psychic"), 100),
    )
}